<?php
/**
 * Created by PhpStorm.
 * User: momon
 * Date: 20.11.2016
 * Time: 19:59
 */

namespace app\components;
use yii\base\Widget;


class AfterSearchWidget extends Widget
{
    public $items;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('afterSearch',[
            'items' => $this->items,
        ]);
    }
}