<?php
/**
 * Created by PhpStorm.
 * User: Alpha3
 * Date: 21.11.2016
 * Time: 17:53
 */

namespace app\components;
use yii\base\Widget;


class MenuWidgets extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('menu');
    }
}