<?php

namespace app\components;

use app\models\Items;
use app\models\Locality;
use yii\base\Widget;

class SearchWidget extends Widget
{
    public $items;
    public $city;

    public function init()
    {
        $this->items = new Items();
        $this->city = new Locality();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('searchItems',[
            'items' => $this->items,
            'city' => $this->city,
        ]);
    }
}