<?php


namespace app\components;
use app\models\SubCat;
use app\models\Topmenu;
use app\models\TopSub;
use yii\base\Widget;
use Yii;

/**
 * Class WidgetTopMenu
 * @package app\components
 */
class WidgetTopMenu extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $menu = new Topmenu();
        $menus = $menu->getTopMenu();
        $count_menus = count($menus);
        $modelTopSubmenu = new TopSub();

        $list_sub_categoryes = $modelTopSubmenu->getList();
        $model = array();
        foreach ($list_sub_categoryes as $key => $item){
            $count_model = $modelTopSubmenu->getListSubMenu($item->id_top);
            foreach ($count_model as $i => $id_title)
                $model[$key][$i] = Yii::t('cabinet', 'sub_menu')[$id_title->idSub->title];
        }
        $count_model = count($model);

        return $this->render('top_menu',[
            'menus' => $menus,
            'count_menus' => $count_menus,
            'sub_menus' => $model,
            'count_sub_menus' => $count_model
        ]);
    }
}